#eureka client配置
eureka:
  instance:
    # 注册时使用ip而不是主机名
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    health-check-url-path: /actuator/health
    # 状态地址为api地址
    statusPageUrlPath: /${server.servlet.contextpath:}/apidoc.html
    leaseRenewalIntervalInSeconds: 20 #租期更新时间间隔（默认30秒）
    leaseExpirationDurationInSeconds: 60 #租期到期时间（默认90秒）


eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

server:
  port: 8001

spring:
  application:
    name: customer

  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.steven.customer
  mapper-locations: classpath*:mapper/*Mapper.xml

### console show sql log / mybatis log plugin show sql log
logging:
  level:
    com: debug
